{
 "title": "JokerCynic - PromEx Bot Dashboard",
 "tags": [
  "PromEx",
  "joker_cynic",
  "Bot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,5m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Bot handle time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(joker_cynic_prom_ex_bot_handle_time_bucket[$interval]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Money consumption",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(joker_cynic_prom_ex_bot_ai_prompt_tokens_sum{model=\"gpt-4o-mini-2024-07-18\"}[1d])\n  - min_over_time(joker_cynic_prom_ex_bot_ai_prompt_tokens_sum{model=\"gpt-4o-mini-2024-07-18\"}[1d])\n) * 0.0432 / 1000\n+\n(\n  max_over_time(joker_cynic_prom_ex_bot_ai_completion_tokens_sum{model=\"gpt-4o-mini-2024-07-18\"}[1d])\n  - min_over_time(joker_cynic_prom_ex_bot_ai_completion_tokens_sum{model=\"gpt-4o-mini-2024-07-18\"}[1d])\n) * 0.1728 / 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 13 },
   "targets": [
    {
     "expr": "sum by (model) (increase(joker_cynic_prom_ex_bot_ai_total_tokens_sum[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 21 },
   "targets": [
    {
     "expr": "sum by (model) (increase(joker_cynic_prom_ex_bot_ai_total_tokens_counter[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}