import Config

# Configure your database
config :joker_cynic, JokerCynic.PromEx,
  grafana: [
    folder_name: "JokerCynic",
    host: "http://localhost:3000",
    username: "admin",
    password: "grafana",
    upload_dashboards_on_start: true
  ],
  metrics_server: :disabled

config :joker_cynic, JokerCynic.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "joker_cynic_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :joker_cynic, JokerCynicWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "KHtSUJ4dL2DGbMoJj65znFmQmScoqQ6v4SLrSHhGW1IOcA+LTy9nuI0GO3rvhyU7",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:joker_cynic, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:joker_cynic, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :joker_cynic, JokerCynicWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/joker_cynic_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

config :joker_cynic, :metrics_auth_token, "Bearer my-super-secret"

# Enable dev routes for dashboard and mailbox
config :joker_cynic, dev_routes: true

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :unplug, :init_mode, :runtime
