import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :joker_cynic, JokerCynicWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :joker_cynic,
  nikita_id: 562_754_575,
  nikita_chat_id: -1_001_549_164_880,
  nikita_counter_timeout_min: 25

# Do not print debug messages in production
config :logger, level: :info

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: JokerCynic.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
